//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samples.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileProviderResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileProviderResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Samples.Properties.FileProviderResources", typeof(FileProviderResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The only supported number of query filters is {0}.  The actual number of filters in the query is {1}..
        /// </summary>
        internal static string ExceptionFilterCountTemplate {
            get {
                return ResourceManager.GetString("ExceptionFilterCountTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameters..
        /// </summary>
        internal static string ExceptionInvalidParameters {
            get {
                return ResourceManager.GetString("ExceptionInvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid patch..
        /// </summary>
        internal static string ExceptionInvalidPatch {
            get {
                return ResourceManager.GetString("ExceptionInvalidPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resource..
        /// </summary>
        internal static string ExceptionInvalidResource {
            get {
                return ResourceManager.GetString("ExceptionInvalidResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resource identifier..
        /// </summary>
        internal static string ExceptionInvalidResourceIdentifier {
            get {
                return ResourceManager.GetString("ExceptionInvalidResourceIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving the members of a group is not supported, because it is impractical..
        /// </summary>
        internal static string ExceptionRetrievingGroupMembersNotSupported {
            get {
                return ResourceManager.GetString("ExceptionRetrievingGroupMembersNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported query..
        /// </summary>
        internal static string ExceptionUnsupportedQuery {
            get {
                return ResourceManager.GetString("ExceptionUnsupportedQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing a request to create an  entry with this source identifier: {0}..
        /// </summary>
        internal static string InformationCreating {
            get {
                return ResourceManager.GetString("InformationCreating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing a request to delete a {0} entry with this identifier: {1}..
        /// </summary>
        internal static string InformationDeleting {
            get {
                return ResourceManager.GetString("InformationDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing a request to patch a {0}  entry with this identifier: {1}..
        /// </summary>
        internal static string InformationPatching {
            get {
                return ResourceManager.GetString("InformationPatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing a request to retrieve a  {0} entry with this identifier: {1}..
        /// </summary>
        internal static string InformationRetrieving {
            get {
                return ResourceManager.GetString("InformationRetrieving", resourceCulture);
            }
        }
    }
}
