//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samples {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProvisioningAgentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProvisioningAgentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Samples.ProvisioningAgentResources", typeof(ProvisioningAgentResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CorrelationIdentifier: {0} 
        ///{1} Time: {2:O} Thread Identifier: {3} Thread Name: {4} Machine Name: {5}.
        /// </summary>
        internal static string AnnotatedEmissionTemplate {
            get {
                return ResourceManager.GetString("AnnotatedEmissionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The only supported number of query filters is {0}.  The actual number of filters in the query is {1}.
        /// </summary>
        internal static string ExceptionFilterCountTemplate {
            get {
                return ResourceManager.GetString("ExceptionFilterCountTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid member.
        /// </summary>
        internal static string ExceptionInvalidMember {
            get {
                return ResourceManager.GetString("ExceptionInvalidMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid parameters.
        /// </summary>
        internal static string ExceptionInvalidParameters {
            get {
                return ResourceManager.GetString("ExceptionInvalidParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid patch.
        /// </summary>
        internal static string ExceptionInvalidPatch {
            get {
                return ResourceManager.GetString("ExceptionInvalidPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resource.
        /// </summary>
        internal static string ExceptionInvalidResource {
            get {
                return ResourceManager.GetString("ExceptionInvalidResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resource identifier.
        /// </summary>
        internal static string ExceptionInvalidResourceIdentifier {
            get {
                return ResourceManager.GetString("ExceptionInvalidResourceIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving the members of a group is not supported, because it is impractical.
        /// </summary>
        internal static string ExceptionRetrievingGroupMembersNotSupported {
            get {
                return ResourceManager.GetString("ExceptionRetrievingGroupMembersNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported query.
        /// </summary>
        internal static string ExceptionUnsupportedQuery {
            get {
                return ResourceManager.GetString("ExceptionUnsupportedQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The agent is listening at this address: {0}.
        /// </summary>
        internal static string InformationAgentStartedTemplate {
            get {
                return ResourceManager.GetString("InformationAgentStartedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to listen at this address: {0}.
        /// </summary>
        internal static string InformationBaseAddressTemplate {
            get {
                return ResourceManager.GetString("InformationBaseAddressTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant identifier: {0}.
        /// </summary>
        internal static string InformationTenantIdentifierTemplate {
            get {
                return ResourceManager.GetString("InformationTenantIdentifierTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to terminate this agent.  .
        /// </summary>
        internal static string PromptTerminate {
            get {
                return ResourceManager.GetString("PromptTerminate", resourceCulture);
            }
        }
    }
}
